blank_issues_enabled: false
contact_links:
  - name: Metafy Discord
    url: https://discord.gg/W6PmEjjQsA 
    about: An invite Link to our discord community
  - name: Metafy Website
    url: https://metafy.social
    about: Our official website
