name: 'Welcome New Contributors'

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome-new-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: 'Greet the contributor'
        uses: garg3133/welcome-new-contributors@v1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Thank you for opening your first issue in our repository, one of our maintainers will get in touch with you soon.
            
            **DO NOT FORGET TO ADD METAMASK WALLET ADDRESS IN THE AUTH FORM**
            We at Metafy have some special rewards and swags for the top contributors in general repos and every contributor in web3 repos
            For being eligible for that, please authenticate yourself using this link:
            https://hacktoberfest.auth.metafy.social 
            
            **Rewards : T-shirts & NFT ( for blockchain contributions )**

            Best of luck on your Contributions
            For further queries you can join our discord for support : https://discord.gg/W6PmEjjQsA
          pr-message: |
            Thank you for opening your first pull request in our repository, one of our maintainers will get in touch with you soon.

            **DO NOT FORGET TO ADD METAMASK WALLET ADDRESS IN THE AUTH FORM**
            We at Metafy have some special rewards and swags for the top contributors in general repos and every contributor in web3 repos
            For being eligible for that, please authenticate yourself using this link:
            https://hacktoberfest.auth.metafy.social 

            **Rewards : T-shirts & NFT ( for blockchain contributions )**
            
            Best of luck on your Contributions
            For further queries you can join our discord for support : https://discord.gg/W6PmEjjQsA